name: Hello-world
on: push

jobs:

  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: Dump contents of file
        run: echo "$(cat hello_world.txt)"
      
