name: Echo Secrets and Variables
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "This is not a secret"  # This is a public environment variable

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo environment variable
      run: echo "My environment variable is $MY_VARIABLE" # This is your variable that will not be masked

    - name: Echo GitHub secret
      run: echo "My GitHub secret is ${{ secrets.NEW_SECRET }}" # This is the secret you added in a previous step

    - name: Echo GitHub variable
      run: echo " My github variable is ${{ vars.NEW_VARIABLE }}"
      
  anothetest:
    runs-on: ubuntu-latest
    environment:
      name: My Environment
    env:
      # this will take the entire vars context configured in the repository > environments
      # setting and convert it to JSON so we can automatically assign all the values to the
      # runner's environment
      VARS_CONTEXT: ${{ toJson(vars) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set env vars from vars context JSON
        run: |
          # Pipe the JSON string into jq
          echo "$VARS_CONTEXT" | 
          # Convert JSON object into an array of key-value pairs
          jq -r 'to_entries | 
          # Map over each key-value pair
          .[] | 
          # Format each pair as "KEY=VALUE" and append it all to the environment file
          "\(.key)=\(.value)"' >> $GITHUB_ENV
      - name: Check env
        run: printenv
      
